#!/usr/bin/env bash

if [[ -n $(git status --porcelain) ]]; then
	printf "\e[31;1m%s\e[0m\n" '원격 저장소에 Push 하기 위해 코드를 테스트 하려 합니다.
테스트에 영향을 주지 않도록 commit 하지 않은 변경사항을 모두 commit 하거나 stash 에 저장하세요.'
	exit 1
fi

printf "\e[33;1m%s\e[0m\n" '단위 테스트 실행'
dart test
if [[ $? -ne 0 ]]; then
	printf "\e[31;1m%s\e[0m\n" '단위 테스트 에러'
	exit 1
fi
printf "\e[33;1m%s\e[0m\n" '단위 테스트 완료'
