#!/usr/bin/env bash

printf "\e[33;1m%s\e[0m\n" 'Pre-Commit'

# Undo the stash of the files
pop_stash_files() {
	if [[ -n ${hasChanges} ]]; then
		printf "\e[33;1m%s\e[0m\n" '=== 잠시 stash 로 넣은 변경파일을 다시 가져옵니다 ==='
		git stash pop
	fi
}

# Stash unstaged files
hasChanges=$(git diff)
if [[ -n ${hasChanges} ]]; then
	printf "\e[33;1m%s\e[0m\n" 'stage 되지 않은 파일을 잠시 stash에 넣습니다.'
	git stash push --keep-index
fi

# Flutter formatter
printf "\e[33;1m%s\e[0m\n" 'Dart 코드 포맷팅을 시작'
dart format --output=none --set-exit-if-changed .
printf "\e[33;1m%s\e[0m\n" 'Dart 코드 포맷팅 완료'

hasNewFilesFormatted=$(git diff)
if [[ -n ${hasNewFilesFormatted} ]]; then
	git add .
	printf "\e[33;1m%s\e[0m\n" 'Formatting 된 파일이 stage로 이동 되었음'
fi

printf "\e[33;1m%s\e[0m\n" 'Dart 코드 분석 실행'
if ! flutter analyze; then
	printf "\e[31;1m%s\e[0m\n" '=== 분석 에러 ==='
	pop_stash_files
	exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Dart 코드 분석 완료'

pop_stash_files
