name: Continuous Integration Workflow

permissions:
  actions: read

on: [push, pull_request]

jobs:
  spell_check:
    uses: ./.github/workflows/spell_checker.yaml
  flutter_ci:
    uses: ./.github/workflows/flutter_analyzer.yaml
