name: Continuous Integration Workflow

permissions:
  actions: write

on: [push, pull_request]

jobs:
  cacher:
    uses: ./.github/workflows/cacher.yaml

  flutter_code_checker:
    uses: ./.github/workflows/flutter_analyzer.yaml

  spell_checker:
    uses: ./.github/workflows/spell_checker.yaml
