name: Continuous Integration Workflow

permissions:
  actions: write

on: [push, pull_request]

jobs:
  cacher:
    uses: ./.github/workflows/cacher.yaml
  flutter_ci:
    uses: ./.github/workflows/flutter_analyzer.yaml
    needs: cacher
  spell_check:
    uses: ./.github/workflows/spell_checker.yaml
