name: Continuous Integration Workflow

permissions:
  actions: write

on: [push, pull_request]

jobs:
  flutter_ci:
    uses: ./.github/workflows/flutter_analyzer.yaml

  spell_check:
    uses: ./.github/workflows/spell_checker.yaml
