name: Continuous Integration Workflow

permissions:
  actions: write

on: [push, pull_request]

jobs:
  cache_trimmer:
    uses: ./.github/workflows/cache_prunner.yaml

  flutter_code_checker:
    uses: ./.github/workflows/flutter_analyzer.yaml

  spell_checker:
    uses: ./.github/workflows/spell_checker.yaml
