# Repo의 Actions 탭에 나타날 workflow 이름으로 필수 옵션 아님
name: Continuous Integration

permissions:
  actions: write

on: [push, pull_request]

jobs:
  flutter_ci:
    uses: ./.github/workflows/flutter.yaml
  spell_check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
