# Repo의 Actions 탭에 나타날 workflow 이름으로 필수 옵션 아님
name: Continuous Integration

permissions:
  actions: write

on: [push, pull_request]

jobs:
  ci:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Start Flutter Continuous Integration
        uses: ./.github/workflows/flutter.yaml
