name: Flutter CI

permissions:
  actions: write

on: workflow_call

jobs:
  flutter_ci:
    name: Flutter CI
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable]
        version: [3.13.8]

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.working-directory }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: ${{ env.working-directory }}

      - name: Analyze project source
        run: flutter analyze
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ env.working-directory }}
